version: '3.8'
services:
  catalog:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sd-catalog-backend
    image: sd-catalog-backend:latest
    restart: unless-stopped
    environment:
      MONGODB_DATABASE: "sda_catalog"
      MONGODB_HOSTNAME: mongodb
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: admin
    ports:
      - "5000:5000"
    volumes:
      - appdata:/home/www
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin 
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: sda_catalog
      MONGODB_DATA_DIR: /data/db
      MONGODB_LOG_DIR: /dev/null
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  appdata:
    driver: local
  mongodbdata:
    driver: local